#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ "$(uname -s)" = "Linux" ] && [ -f "/etc/debian_version" ]; then

  # Install geda if needed
  which xgsch2pcb >/dev/null 2>&1  || {
    echo "==> Installing Dependencie"
    sudo apt-get update && sudo apt-get install -y geda geda-xgsch2pcb
  }
elif [ "$(uname -s)" = "Linux" ] && [ -f "/etc/arch-release" ]; then

  # Install geda if needed
  which gsch2pcb >/dev/null 2>&1  || {
    echo "==> Installing Dependencie"
    sudo pacman -S geda-gaf pcb
  }
else
  echo "Sorry, only support Debain system."
  exit 1
fi
